picross_site/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from picross_site.forms import UserLoginForm
from picross_site.models import User, db
from werkzeug.security import check_password_hash

from flask_login import login_user, logout_user, current_user, login_required



auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            username= form.username.data
            password = form.password.data
            print(email, username)

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {username}', 'user-created')

            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: please check your form')
    return render_template('signup.html', form=form)



@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
   
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                print(f"this is the logged user: {logged_user}")
                login_user(logged_user)
                flash(f"You were successfully logged in: Via email/password", "auth-success")
                return redirect(url_for('site.profile'))

            else: 
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    
    except:
        raise Exception('Invalid Form Data: Please check your Form')

    return render_template('signin.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

picross_site/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from picross_site.forms import PuzzleForm
from picross_site.models import Puzzle, db

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    print("ooga booga in the terminal")
    return render_template('index.html')

@site.route('/profile', methods = ['GET','POST'])
@login_required
def profile():
    my_puzzle = PuzzleForm()

    try:
        if request.method == 'POST' and my_puzzle.validate_on_submit():
            descriptor = my_puzzle.descriptor.data
            puzzle_data = my_puzzle.puzzle_data.data
            user_token = current_user.token

            puzzle = Puzzle( descriptor, puzzle_data, user_token)
            # print(puzzle)
            db.session.add(puzzle)
            db.session.commit()

            return redirect(url_for('site.profile'))

    except:
        raise Exception('Puzzle not added, please check your form and try again!') 

    current_user_token = current_user.token

    puzzles = Puzzle.query.filter_by(user_token=current_user_token)

    return render_template('profile.html', form=my_puzzle, puzzles = puzzles)


# @site.route('/puzzle_page')
# @login_required
# def puzzle_page():
    
#     return render_template('puzzle_page.html')

picross_site/templates/baseline.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Picross Puzzle Mania!</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--  -->
    <!-- <meta http-equiv="refresh" content="3"> -->
    <!--  -->

    <!-- Bootswatch 5.2.3, replacing bootstrap -->
    <link href=" https://cdn.jsdelivr.net/npm/bootswatch@5.2.3/dist/cerulean/bootstrap.min.css " rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='css/main.css')}}">

    <!-- Bootstrap CSS v5.2.1 -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
       rel="stylesheet"
       integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
       crossorigin="anonymous"> -->
</head>

<body>
    <!-- beginning of navbar -->
    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="nav navbar-nav">
            <a class="nav-item nav-link active" href="{{ url_for('site.home') }}" aria-current="page">Home <span class="visually-hidden">(current)</span></a>
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('site.profile') }}">Profile</a>

            <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
           
            <a class="nav-item nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
            {% endif %}
        </div>
    </nav>
    <!-- end of navbar -->
    <main>

        <!-- this section block the child-templates can override -->

        <div class="container">
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </main>
    <footer>
        <!-- place footer here -->
    </footer>

    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
        integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
        </script>
</body>

</html>

picross_site/templates/forms.html
<!-- HTML produced by the FLask Form -->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class="form-control", placeholder = "Place Username Here") }}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder = "Place Email Here") }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder = "Place Password Here") }}
        </fieldset>
        <!-- now for submit button -->
        {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}
    </div>
</form>

picross_site/templates/puzzle_form.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="descriptor-field">
            {{ form.descriptor.label }}
            {{ form.descriptor(class = "form-control", placeholder="Descriptor") }}
        </fieldset>
        <fieldset id="puzzle_data-field">
            {{ form.puzzle_data.label }}
            {{ form.puzzle_data(class = "form-control", placeholder="Puzzle Data") }}
        </fieldset>
        <!-- Submit Button Area -->
        {{ form.submit_button(class="btn btn-primary btn-block mt-2") }}

    </div>
</form>

picross_site/templates/puzzle_page.html
{% extends 'baseline.html' %}
{% block content %}
{# {% include 'navigation.html' %} #}
<div id="puzzle_box" class='container'>
    <div class="row" id="row-1">
        {# <div class="col col-2" id="r0c0"></div> #}
        <div class="col justify-content-center d-flex " id="BSr-1c1">
            <div class="button-holder p-2">
                <button method="post" type="submit" class="btn btn-sm btn-outline-info" id="btnPop">Populate Headers</button>
                <button type="button" class="btn btn-sm btn-outline-success" id="btnSubmit">Submit Answer!</button>
                <button type="button" class="btn btn-sm btn-outline-primary" id='btnSave'>Save</button>
                <button type="button" class="btn btn-sm btn-outline-danger" id="btnLoad">Load</button>
            </div>
        </div>

    </div>
    <div class="row" id="row0">

        <div class="col justify-content-center d-flex" id="BSr0c1"></div>

    </div>
    <div class="row" id="row1">

        <div class="col justify-content-center d-flex" id="BSr1c1"></div>

    </div>
</div>
{% endblock content %}